[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
missing_signer_check = "HVDgr5PCwyH1bGkVvB6sDqzDkjZq6FfC8qE38PV2Z8Fc"
missing_owner_check = "GMDYqj3bRYPjUCKPF6wHPUxZZgWDhPPKxdTfUmFN8jj8"
arithmetic_overflow = "5Z7MxiEHuVqN6xv5f7g3T4XFhQZnYSGGPHjFa8E5Rx6w"
account_data_matching = "8F1QcGh5RLKvZGJHxYFtN3TqZX2E8aVFfpwYL4NxH2Am"
arbitrary_cpi = "D3fWpLnJg5F6xN8E7vQ2cYZhB5XmK4RxL9TaPbV2Jn5s"
reentrance_attack = "BKm7nRJsPzQ3xH2fL9VTcW5Eg8YqX4NaZ6vD2MpF8kLx"
type_cosplay = "CnV2bXqZ5F7kL8TmW3R9YpE4HxG6JaNf2DsU7BwK5Mqh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[[test.genesis]]
address = "HVDgr5PCwyH1bGkVvB6sDqzDkjZq6FfC8qE38PV2Z8Fc"
program = "target/deploy/missing_signer_check.so"

[[test.genesis]]
address = "GMDYqj3bRYPjUCKPF6wHPUxZZgWDhPPKxdTfUmFN8jj8"
program = "target/deploy/missing_owner_check.so"

[[test.genesis]]
address = "5Z7MxiEHuVqN6xv5f7g3T4XFhQZnYSGGPHjFa8E5Rx6w"
program = "target/deploy/arithmetic_overflow.so"

[[test.genesis]]
address = "8F1QcGh5RLKvZGJHxYFtN3TqZX2E8aVFfpwYL4NxH2Am"
program = "target/deploy/account_data_matching.so"

[[test.genesis]]
address = "D3fWpLnJg5F6xN8E7vQ2cYZhB5XmK4RxL9TaPbV2Jn5s"
program = "target/deploy/arbitrary_cpi.so"

[[test.genesis]]
address = "BKm7nRJsPzQ3xH2fL9VTcW5Eg8YqX4NaZ6vD2MpF8kLx"
program = "target/deploy/reentrance_attack.so"

[[test.genesis]]
address = "CnV2bXqZ5F7kL8TmW3R9YpE4HxG6JaNf2DsU7BwK5Mqh"
program = "target/deploy/type_cosplay.so"
