[package]
name = "type-cosplay"
version = "0.1.0"
description = "Educational example: Type Cosplay (discriminator) vulnerability"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "type_cosplay"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.31.1"
